
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: deploymentCronjob
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: kubectl
            image: bitnami/kubectl
            command:
              - 'kubectl'
              - 'rollout'
              - 'restart'
              - 'deployment/devopsProject'
            env:
              - name: varName
                value: varValue
