apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness
  labels:
    app: readiness
    
spec:
  selector:
    matchLabels:
      app: readiness
  template:
    metadata:
      labels:
        app: readiness
    spec:
      containers:
      - name: readiness # Name of container in the pod.
        image: kamranazeem/k8s-probes-demo:latest
        # imagePullPolicy: Always

        env:
        - name: START_DELAY
          value: "30" # Double quotes for ENV variables are important.

        ports:
        - name: http 
          containerPort: 80

        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 5m
            memory: 20Mi


        readinessProbe:
          httpGet:
            path: /readinesscheck.txt
            port: 80
          initialDelaySeconds: 5

          # Retry the probe every X seconds (frequency):
          periodSeconds: 2

          # Number of times this probe can fail ,
          #   before kubernetes gives up and marks the "pod" as "Unready":
          failureThreshold: 30

          # In the case above, the Pod will be marked "Unready",
          #   if the probe does not pass 2 x 30 = 60 seconds.
          successThreshold: 1

---

apiVersion: v1
kind: Service
metadata:
  name: readiness
  labels:
    app: readiness
spec:
  ports:
    - port: 80
  selector:
    app: readiness
  type: ClusterIP
